export type CityGeoId = {
  geoId: string,
  geoIdState: string,
  city: string,
  state: string,
};

export type CityGeoIdArray = {
  geoId: string,
  geoIdState: string,
  city: string,
  state: string,
}[];

export const GEO_IDS: CityGeoIdArray = [
  { geoId: "geoId/0107000", geoIdState: "geoId/01", city: "Birmingham", state: "Alabama" },
  { geoId: "geoId/0135896", geoIdState: "geoId/01", city: "Hoover", state: "Alabama" },
  { geoId: "geoId/0137000", geoIdState: "geoId/01", city: "Huntsville", state: "Alabama" },
  { geoId: "geoId/0150000", geoIdState: "geoId/01", city: "Mobile", state: "Alabama" },
  { geoId: "geoId/0151000", geoIdState: "geoId/01", city: "Montgomery", state: "Alabama" },
  { geoId: "geoId/0177256", geoIdState: "geoId/01", city: "Tuscaloosa", state: "Alabama" },
  { geoId: "geoId/0203000", geoIdState: "geoId/02", city: "Anchorage municipality", state: "Alaska" },
  { geoId: "geoId/0404720", geoIdState: "geoId/04", city: "Avondale", state: "Arizona" },
  { geoId: "geoId/0412000", geoIdState: "geoId/04", city: "Chandler", state: "Arizona" },
  { geoId: "geoId/0427400", geoIdState: "geoId/04", city: "Gilbert", state: "Arizona" },
  { geoId: "geoId/0427820", geoIdState: "geoId/04", city: "Glendale", state: "Arizona" },
  { geoId: "geoId/0446000", geoIdState: "geoId/04", city: "Mesa", state: "Arizona" },
  { geoId: "geoId/0454050", geoIdState: "geoId/04", city: "Peoria", state: "Arizona" },
  { geoId: "geoId/0455000", geoIdState: "geoId/04", city: "Phoenix", state: "Arizona" },
  { geoId: "geoId/0465000", geoIdState: "geoId/04", city: "Scottsdale", state: "Arizona" },
  { geoId: "geoId/0471510", geoIdState: "geoId/04", city: "Surprise", state: "Arizona" },
  { geoId: "geoId/0473000", geoIdState: "geoId/04", city: "Tempe", state: "Arizona" },
  { geoId: "geoId/0477000", geoIdState: "geoId/04", city: "Tucson", state: "Arizona" },
  { geoId: "geoId/0485540", geoIdState: "geoId/04", city: "Yuma", state: "Arizona" },
  { geoId: "geoId/0523290", geoIdState: "geoId/05", city: "Fayetteville", state: "Arkansas" },
  { geoId: "geoId/0524550", geoIdState: "geoId/05", city: "Fort Smith", state: "Arkansas" },
  { geoId: "geoId/0535710", geoIdState: "geoId/05", city: "Jonesboro", state: "Arkansas" },
  { geoId: "geoId/0541000", geoIdState: "geoId/05", city: "Little Rock", state: "Arkansas" },
  { geoId: "geoId/0566080", geoIdState: "geoId/05", city: "Springdale", state: "Arkansas" },
  { geoId: "geoId/0600562", geoIdState: "geoId/06", city: "Alameda", state: "California" },
  { geoId: "geoId/0600884", geoIdState: "geoId/06", city: "Alhambra", state: "California" },
  { geoId: "geoId/0602000", geoIdState: "geoId/06", city: "Anaheim", state: "California" },
  { geoId: "geoId/0602252", geoIdState: "geoId/06", city: "Antioch", state: "California" },
  { geoId: "geoId/0602364", geoIdState: "geoId/06", city: "Apple Valley", state: "California" },
  { geoId: "geoId/0603526", geoIdState: "geoId/06", city: "Bakersfield", state: "California" },
  { geoId: "geoId/0603666", geoIdState: "geoId/06", city: "Baldwin Park", state: "California" },
  { geoId: "geoId/0604982", geoIdState: "geoId/06", city: "Bellflower", state: "California" },
  { geoId: "geoId/0606000", geoIdState: "geoId/06", city: "Berkeley", state: "California" },
  { geoId: "geoId/0608786", geoIdState: "geoId/06", city: "Buena Park", state: "California" },
  { geoId: "geoId/0608954", geoIdState: "geoId/06", city: "Burbank", state: "California" },
  { geoId: "geoId/0611194", geoIdState: "geoId/06", city: "Carlsbad", state: "California" },
  { geoId: "geoId/0611530", geoIdState: "geoId/06", city: "Carson", state: "California" },
  { geoId: "geoId/0613014", geoIdState: "geoId/06", city: "Chico", state: "California" },
  { geoId: "geoId/0613210", geoIdState: "geoId/06", city: "Chino", state: "California" },
  { geoId: "geoId/0613214", geoIdState: "geoId/06", city: "Chino Hills", state: "California" },
  { geoId: "geoId/0613392", geoIdState: "geoId/06", city: "Chula Vista", state: "California" },
  { geoId: "geoId/0613588", geoIdState: "geoId/06", city: "Citrus Heights", state: "California" },
  { geoId: "geoId/0614218", geoIdState: "geoId/06", city: "Clovis", state: "California" },
  { geoId: "geoId/0615044", geoIdState: "geoId/06", city: "Compton", state: "California" },
  { geoId: "geoId/0616000", geoIdState: "geoId/06", city: "Concord", state: "California" },
  { geoId: "geoId/0616350", geoIdState: "geoId/06", city: "Corona", state: "California" },
  { geoId: "geoId/0616532", geoIdState: "geoId/06", city: "Costa Mesa", state: "California" },
  { geoId: "geoId/0617918", geoIdState: "geoId/06", city: "Daly City", state: "California" },
  { geoId: "geoId/0619766", geoIdState: "geoId/06", city: "Downey", state: "California" },
  { geoId: "geoId/0621712", geoIdState: "geoId/06", city: "El Cajon", state: "California" },
  { geoId: "geoId/0622020", geoIdState: "geoId/06", city: "Elk Grove", state: "California" },
  { geoId: "geoId/0622230", geoIdState: "geoId/06", city: "El Monte", state: "California" },
  { geoId: "geoId/0622804", geoIdState: "geoId/06", city: "Escondido", state: "California" },
  { geoId: "geoId/0623182", geoIdState: "geoId/06", city: "Fairfield", state: "California" },
  { geoId: "geoId/0624638", geoIdState: "geoId/06", city: "Folsom", state: "California" },
  { geoId: "geoId/0624680", geoIdState: "geoId/06", city: "Fontana", state: "California" },
  { geoId: "geoId/0626000", geoIdState: "geoId/06", city: "Fremont", state: "California" },
  { geoId: "geoId/0627000", geoIdState: "geoId/06", city: "Fresno", state: "California" },
  { geoId: "geoId/0628000", geoIdState: "geoId/06", city: "Fullerton", state: "California" },
  { geoId: "geoId/0629000", geoIdState: "geoId/06", city: "Garden Grove", state: "California" },
  { geoId: "geoId/0630000", geoIdState: "geoId/06", city: "Glendale", state: "California" },
  { geoId: "geoId/0632548", geoIdState: "geoId/06", city: "Hawthorne", state: "California" },
  { geoId: "geoId/0633000", geoIdState: "geoId/06", city: "Hayward", state: "California" },
  { geoId: "geoId/0633182", geoIdState: "geoId/06", city: "Hemet", state: "California" },
  { geoId: "geoId/0633434", geoIdState: "geoId/06", city: "Hesperia", state: "California" },
  { geoId: "geoId/0636000", geoIdState: "geoId/06", city: "Huntington Beach", state: "California" },
  { geoId: "geoId/0636448", geoIdState: "geoId/06", city: "Indio", state: "California" },
  { geoId: "geoId/0636546", geoIdState: "geoId/06", city: "Inglewood", state: "California" },
  { geoId: "geoId/0636770", geoIdState: "geoId/06", city: "Irvine", state: "California" },
  { geoId: "geoId/0639496", geoIdState: "geoId/06", city: "Lake Forest", state: "California" },
  { geoId: "geoId/0639892", geoIdState: "geoId/06", city: "Lakewood", state: "California" },
  { geoId: "geoId/0640130", geoIdState: "geoId/06", city: "Lancaster", state: "California" },
  { geoId: "geoId/0641992", geoIdState: "geoId/06", city: "Livermore", state: "California" },
  { geoId: "geoId/0643000", geoIdState: "geoId/06", city: "Long Beach", state: "California" },
  { geoId: "geoId/0644000", geoIdState: "geoId/06", city: "Los Angeles", state: "California" },
  { geoId: "geoId/0644574", geoIdState: "geoId/06", city: "Lynwood", state: "California" },
  { geoId: "geoId/0645484", geoIdState: "geoId/06", city: "Manteca", state: "California" },
  { geoId: "geoId/0646842", geoIdState: "geoId/06", city: "Menifee", state: "California" },
  { geoId: "geoId/0646898", geoIdState: "geoId/06", city: "Merced", state: "California" },
  { geoId: "geoId/0647766", geoIdState: "geoId/06", city: "Milpitas", state: "California" },
  { geoId: "geoId/0648256", geoIdState: "geoId/06", city: "Mission Viejo", state: "California" },
  { geoId: "geoId/0648354", geoIdState: "geoId/06", city: "Modesto", state: "California" },
  { geoId: "geoId/0649270", geoIdState: "geoId/06", city: "Moreno Valley", state: "California" },
  { geoId: "geoId/0649670", geoIdState: "geoId/06", city: "Mountain View", state: "California" },
  { geoId: "geoId/0650076", geoIdState: "geoId/06", city: "Murrieta", state: "California" },
  { geoId: "geoId/0650258", geoIdState: "geoId/06", city: "Napa", state: "California" },
  { geoId: "geoId/0651182", geoIdState: "geoId/06", city: "Newport Beach", state: "California" },
  { geoId: "geoId/0652526", geoIdState: "geoId/06", city: "Norwalk", state: "California" },
  { geoId: "geoId/0653000", geoIdState: "geoId/06", city: "Oakland", state: "California" },
  { geoId: "geoId/0653322", geoIdState: "geoId/06", city: "Oceanside", state: "California" },
  { geoId: "geoId/0653896", geoIdState: "geoId/06", city: "Ontario", state: "California" },
  { geoId: "geoId/0653980", geoIdState: "geoId/06", city: "Orange", state: "California" },
  { geoId: "geoId/0654652", geoIdState: "geoId/06", city: "Oxnard", state: "California" },
  { geoId: "geoId/0655156", geoIdState: "geoId/06", city: "Palmdale", state: "California" },
  { geoId: "geoId/0656000", geoIdState: "geoId/06", city: "Pasadena", state: "California" },
  { geoId: "geoId/0656700", geoIdState: "geoId/06", city: "Perris", state: "California" },
  { geoId: "geoId/0657792", geoIdState: "geoId/06", city: "Pleasanton", state: "California" },
  { geoId: "geoId/0658072", geoIdState: "geoId/06", city: "Pomona", state: "California" },
  { geoId: "geoId/0659451", geoIdState: "geoId/06", city: "Rancho Cucamonga", state: "California" },
  { geoId: "geoId/0659920", geoIdState: "geoId/06", city: "Redding", state: "California" },
  { geoId: "geoId/0659962", geoIdState: "geoId/06", city: "Redlands", state: "California" },
  { geoId: "geoId/0660018", geoIdState: "geoId/06", city: "Redondo Beach", state: "California" },
  { geoId: "geoId/0660102", geoIdState: "geoId/06", city: "Redwood City", state: "California" },
  { geoId: "geoId/0660466", geoIdState: "geoId/06", city: "Rialto", state: "California" },
  { geoId: "geoId/0660620", geoIdState: "geoId/06", city: "Richmond", state: "California" },
  { geoId: "geoId/0662000", geoIdState: "geoId/06", city: "Riverside", state: "California" },
  { geoId: "geoId/0662938", geoIdState: "geoId/06", city: "Roseville", state: "California" },
  { geoId: "geoId/0664000", geoIdState: "geoId/06", city: "Sacramento", state: "California" },
  { geoId: "geoId/0664224", geoIdState: "geoId/06", city: "Salinas", state: "California" },
  { geoId: "geoId/0665000", geoIdState: "geoId/06", city: "San Bernardino", state: "California" },
  { geoId: "geoId/0665042", geoIdState: "geoId/06", city: "San Buenaventura (Ventura)", state: "California" },
  { geoId: "geoId/0666000", geoIdState: "geoId/06", city: "San Diego", state: "California" },
  { geoId: "geoId/0667000", geoIdState: "geoId/06", city: "San Francisco", state: "California" },
  { geoId: "geoId/0668000", geoIdState: "geoId/06", city: "San Jose", state: "California" },
  { geoId: "geoId/0668084", geoIdState: "geoId/06", city: "San Leandro", state: "California" },
  { geoId: "geoId/0668196", geoIdState: "geoId/06", city: "San Marcos", state: "California" },
  { geoId: "geoId/0668252", geoIdState: "geoId/06", city: "San Mateo", state: "California" },
  { geoId: "geoId/0668378", geoIdState: "geoId/06", city: "San Ramon", state: "California" },
  { geoId: "geoId/0669000", geoIdState: "geoId/06", city: "Santa Ana", state: "California" },
  { geoId: "geoId/0669070", geoIdState: "geoId/06", city: "Santa Barbara", state: "California" },
  { geoId: "geoId/0669084", geoIdState: "geoId/06", city: "Santa Clara", state: "California" },
  { geoId: "geoId/0669088", geoIdState: "geoId/06", city: "Santa Clarita", state: "California" },
  { geoId: "geoId/0669196", geoIdState: "geoId/06", city: "Santa Maria", state: "California" },
  { geoId: "geoId/0670000", geoIdState: "geoId/06", city: "Santa Monica", state: "California" },
  { geoId: "geoId/0670098", geoIdState: "geoId/06", city: "Santa Rosa", state: "California" },
  { geoId: "geoId/0672016", geoIdState: "geoId/06", city: "Simi Valley", state: "California" },
  { geoId: "geoId/0673080", geoIdState: "geoId/06", city: "South Gate", state: "California" },
  { geoId: "geoId/0675000", geoIdState: "geoId/06", city: "Stockton", state: "California" },
  { geoId: "geoId/0677000", geoIdState: "geoId/06", city: "Sunnyvale", state: "California" },
  { geoId: "geoId/0678120", geoIdState: "geoId/06", city: "Temecula", state: "California" },
  { geoId: "geoId/0678582", geoIdState: "geoId/06", city: "Thousand Oaks", state: "California" },
  { geoId: "geoId/0680000", geoIdState: "geoId/06", city: "Torrance", state: "California" },
  { geoId: "geoId/0680238", geoIdState: "geoId/06", city: "Tracy", state: "California" },
  { geoId: "geoId/0680812", geoIdState: "geoId/06", city: "Turlock", state: "California" },
  { geoId: "geoId/0680854", geoIdState: "geoId/06", city: "Tustin", state: "California" },
  { geoId: "geoId/0681204", geoIdState: "geoId/06", city: "Union City", state: "California" },
  { geoId: "geoId/0681344", geoIdState: "geoId/06", city: "Upland", state: "California" },
  { geoId: "geoId/0681554", geoIdState: "geoId/06", city: "Vacaville", state: "California" },
  { geoId: "geoId/0681666", geoIdState: "geoId/06", city: "Vallejo", state: "California" },
  { geoId: "geoId/0682590", geoIdState: "geoId/06", city: "Victorville", state: "California" },
  { geoId: "geoId/0682954", geoIdState: "geoId/06", city: "Visalia", state: "California" },
  { geoId: "geoId/0682996", geoIdState: "geoId/06", city: "Vista", state: "California" },
  { geoId: "geoId/0684200", geoIdState: "geoId/06", city: "West Covina", state: "California" },
  { geoId: "geoId/0684550", geoIdState: "geoId/06", city: "Westminster", state: "California" },
  { geoId: "geoId/0685292", geoIdState: "geoId/06", city: "Whittier", state: "California" },
  { geoId: "geoId/0803455", geoIdState: "geoId/08", city: "Arvada", state: "Colorado" },
  { geoId: "geoId/0804000", geoIdState: "geoId/08", city: "Aurora", state: "Colorado" },
  { geoId: "geoId/0807850", geoIdState: "geoId/08", city: "Boulder", state: "Colorado" },
  { geoId: "geoId/0812815", geoIdState: "geoId/08", city: "Centennial", state: "Colorado" },
  { geoId: "geoId/0816000", geoIdState: "geoId/08", city: "Colorado Springs", state: "Colorado" },
  { geoId: "geoId/0820000", geoIdState: "geoId/08", city: "Denver", state: "Colorado" },
  { geoId: "geoId/0827425", geoIdState: "geoId/08", city: "Fort Collins", state: "Colorado" },
  { geoId: "geoId/0832155", geoIdState: "geoId/08", city: "Greeley", state: "Colorado" },
  { geoId: "geoId/0843000", geoIdState: "geoId/08", city: "Lakewood", state: "Colorado" },
  { geoId: "geoId/0845970", geoIdState: "geoId/08", city: "Longmont", state: "Colorado" },
  { geoId: "geoId/0846465", geoIdState: "geoId/08", city: "Loveland", state: "Colorado" },
  { geoId: "geoId/0862000", geoIdState: "geoId/08", city: "Pueblo", state: "Colorado" },
  { geoId: "geoId/0877290", geoIdState: "geoId/08", city: "Thornton", state: "Colorado" },
  { geoId: "geoId/0883835", geoIdState: "geoId/08", city: "Westminster", state: "Colorado" },
  { geoId: "geoId/0908000", geoIdState: "geoId/09", city: "Bridgeport", state: "Connecticut" },
  { geoId: "geoId/0918430", geoIdState: "geoId/09", city: "Danbury", state: "Connecticut" },
  { geoId: "geoId/0937000", geoIdState: "geoId/09", city: "Hartford", state: "Connecticut" },
  { geoId: "geoId/0950370", geoIdState: "geoId/09", city: "New Britain", state: "Connecticut" },
  { geoId: "geoId/0952000", geoIdState: "geoId/09", city: "New Haven", state: "Connecticut" },
  { geoId: "geoId/0955990", geoIdState: "geoId/09", city: "Norwalk", state: "Connecticut" },
  { geoId: "geoId/0973000", geoIdState: "geoId/09", city: "Stamford", state: "Connecticut" },
  { geoId: "geoId/0980000", geoIdState: "geoId/09", city: "Waterbury", state: "Connecticut" },
  { geoId: "geoId/1077580", geoIdState: "geoId/10", city: "Wilmington", state: "Delaware" },
  { geoId: "geoId/1150000", geoIdState: "geoId/11", city: "Washington", state: "District of Columbia" },
  { geoId: "geoId/1207300", geoIdState: "geoId/12", city: "Boca Raton", state: "Florida" },
  { geoId: "geoId/1207875", geoIdState: "geoId/12", city: "Boynton Beach", state: "Florida" },
  { geoId: "geoId/1210275", geoIdState: "geoId/12", city: "Cape Coral", state: "Florida" },
  { geoId: "geoId/1212875", geoIdState: "geoId/12", city: "Clearwater", state: "Florida" },
  { geoId: "geoId/1214400", geoIdState: "geoId/12", city: "Coral Springs", state: "Florida" },
  { geoId: "geoId/1216475", geoIdState: "geoId/12", city: "Davie", state: "Florida" },
  { geoId: "geoId/1216725", geoIdState: "geoId/12", city: "Deerfield Beach", state: "Florida" },
  { geoId: "geoId/1217200", geoIdState: "geoId/12", city: "Deltona", state: "Florida" },
  { geoId: "geoId/1224000", geoIdState: "geoId/12", city: "Fort Lauderdale", state: "Florida" },
  { geoId: "geoId/1225175", geoIdState: "geoId/12", city: "Gainesville", state: "Florida" },
  { geoId: "geoId/1230000", geoIdState: "geoId/12", city: "Hialeah", state: "Florida" },
  { geoId: "geoId/1232000", geoIdState: "geoId/12", city: "Hollywood", state: "Florida" },
  { geoId: "geoId/1235000", geoIdState: "geoId/12", city: "Jacksonville", state: "Florida" },
  { geoId: "geoId/1238250", geoIdState: "geoId/12", city: "Lakeland", state: "Florida" },
  { geoId: "geoId/1239425", geoIdState: "geoId/12", city: "Largo", state: "Florida" },
  { geoId: "geoId/1239550", geoIdState: "geoId/12", city: "Lauderhill", state: "Florida" },
  { geoId: "geoId/1243975", geoIdState: "geoId/12", city: "Melbourne", state: "Florida" },
  { geoId: "geoId/1245000", geoIdState: "geoId/12", city: "Miami", state: "Florida" },
  { geoId: "geoId/1245025", geoIdState: "geoId/12", city: "Miami Beach", state: "Florida" },
  { geoId: "geoId/1245060", geoIdState: "geoId/12", city: "Miami Gardens", state: "Florida" },
  { geoId: "geoId/1245975", geoIdState: "geoId/12", city: "Miramar", state: "Florida" },
  { geoId: "geoId/1253000", geoIdState: "geoId/12", city: "Orlando", state: "Florida" },
  { geoId: "geoId/1254000", geoIdState: "geoId/12", city: "Palm Bay", state: "Florida" },
  { geoId: "geoId/1254200", geoIdState: "geoId/12", city: "Palm Coast", state: "Florida" },
  { geoId: "geoId/1255775", geoIdState: "geoId/12", city: "Pembroke Pines", state: "Florida" },
  { geoId: "geoId/1257425", geoIdState: "geoId/12", city: "Plantation", state: "Florida" },
  { geoId: "geoId/1258050", geoIdState: "geoId/12", city: "Pompano Beach", state: "Florida" },
  { geoId: "geoId/1258715", geoIdState: "geoId/12", city: "Port St. Lucie", state: "Florida" },
  { geoId: "geoId/1263000", geoIdState: "geoId/12", city: "St. Petersburg", state: "Florida" },
  { geoId: "geoId/1269700", geoIdState: "geoId/12", city: "Sunrise", state: "Florida" },
  { geoId: "geoId/1270600", geoIdState: "geoId/12", city: "Tallahassee", state: "Florida" },
  { geoId: "geoId/1271000", geoIdState: "geoId/12", city: "Tampa", state: "Florida" },
  { geoId: "geoId/1276600", geoIdState: "geoId/12", city: "West Palm Beach", state: "Florida" },
  { geoId: "geoId/1301052", geoIdState: "geoId/13", city: "Albany", state: "Georgia" },
  { geoId: "geoId/1303440", geoIdState: "geoId/13", city: "Athens", state: "Georgia" },
  { geoId: "geoId/1304000", geoIdState: "geoId/13", city: "Atlanta", state: "Georgia" },
  { geoId: "geoId/1304204", geoIdState: "geoId/13", city: "Augusta", state: "Georgia" },
  { geoId: "geoId/1319000", geoIdState: "geoId/13", city: "Columbus", state: "Georgia" },
  { geoId: "geoId/1342425", geoIdState: "geoId/13", city: "Johns Creek", state: "Georgia" },
  { geoId: "geoId/1349000", geoIdState: "geoId/13", city: "Macon", state: "Georgia" },
  { geoId: "geoId/1367284", geoIdState: "geoId/13", city: "Roswell", state: "Georgia" },
  { geoId: "geoId/1368516", geoIdState: "geoId/13", city: "Sandy Springs", state: "Georgia" },
  { geoId: "geoId/1369000", geoIdState: "geoId/13", city: "Savannah", state: "Georgia" },
  { geoId: "geoId/1380508", geoIdState: "geoId/13", city: "Warner Robins", state: "Georgia" },
  { geoId: "geoId/15003", geoIdState: "geoId/15", city: "Honolulu County", state: "Hawaii" },
  { geoId: "geoId/1608830", geoIdState: "geoId/16", city: "Boise City", state: "Idaho" },
  { geoId: "geoId/1652120", geoIdState: "geoId/16", city: "Meridian", state: "Idaho" },
  { geoId: "geoId/1656260", geoIdState: "geoId/16", city: "Nampa", state: "Idaho" },
  { geoId: "geoId/1702154", geoIdState: "geoId/17", city: "Arlington Heights", state: "Illinois" },
  { geoId: "geoId/1703012", geoIdState: "geoId/17", city: "Aurora", state: "Illinois" },
  { geoId: "geoId/1706613", geoIdState: "geoId/17", city: "Bloomington", state: "Illinois" },
  { geoId: "geoId/1707133", geoIdState: "geoId/17", city: "Bolingbrook", state: "Illinois" },
  { geoId: "geoId/1712385", geoIdState: "geoId/17", city: "Champaign", state: "Illinois" },
  { geoId: "geoId/1714000", geoIdState: "geoId/17", city: "Chicago", state: "Illinois" },
  { geoId: "geoId/1714351", geoIdState: "geoId/17", city: "Cicero", state: "Illinois" },
  { geoId: "geoId/1718823", geoIdState: "geoId/17", city: "Decatur", state: "Illinois" },
  { geoId: "geoId/1723074", geoIdState: "geoId/17", city: "Elgin", state: "Illinois" },
  { geoId: "geoId/1724582", geoIdState: "geoId/17", city: "Evanston", state: "Illinois" },
  { geoId: "geoId/1738570", geoIdState: "geoId/17", city: "Joliet", state: "Illinois" },
  { geoId: "geoId/1751622", geoIdState: "geoId/17", city: "Naperville", state: "Illinois" },
  { geoId: "geoId/1757225", geoIdState: "geoId/17", city: "Palatine", state: "Illinois" },
  { geoId: "geoId/1759000", geoIdState: "geoId/17", city: "Peoria", state: "Illinois" },
  { geoId: "geoId/1765000", geoIdState: "geoId/17", city: "Rockford", state: "Illinois" },
  { geoId: "geoId/1768003", geoIdState: "geoId/17", city: "Schaumburg", state: "Illinois" },
  { geoId: "geoId/1772000", geoIdState: "geoId/17", city: "Springfield", state: "Illinois" },
  { geoId: "geoId/1779293", geoIdState: "geoId/17", city: "Waukegan", state: "Illinois" },
  { geoId: "geoId/1805860", geoIdState: "geoId/18", city: "Bloomington", state: "Indiana" },
  { geoId: "geoId/1810342", geoIdState: "geoId/18", city: "Carmel", state: "Indiana" },
  { geoId: "geoId/1822000", geoIdState: "geoId/18", city: "Evansville", state: "Indiana" },
  { geoId: "geoId/1823278", geoIdState: "geoId/18", city: "Fishers", state: "Indiana" },
  { geoId: "geoId/1825000", geoIdState: "geoId/18", city: "Fort Wayne", state: "Indiana" },
  { geoId: "geoId/1827000", geoIdState: "geoId/18", city: "Gary", state: "Indiana" },
  { geoId: "geoId/1831000", geoIdState: "geoId/18", city: "Hammond", state: "Indiana" },
  { geoId: "geoId/1836003", geoIdState: "geoId/18", city: "Indianapolis city (balance)", state: "Indiana" },
  { geoId: "geoId/1840788", geoIdState: "geoId/18", city: "Lafayette", state: "Indiana" },
  { geoId: "geoId/1851876", geoIdState: "geoId/18", city: "Muncie", state: "Indiana" },
  { geoId: "geoId/1871000", geoIdState: "geoId/18", city: "South Bend", state: "Indiana" },
  { geoId: "geoId/1912000", geoIdState: "geoId/19", city: "Cedar Rapids", state: "Iowa" },
  { geoId: "geoId/1919000", geoIdState: "geoId/19", city: "Davenport", state: "Iowa" },
  { geoId: "geoId/1921000", geoIdState: "geoId/19", city: "Des Moines", state: "Iowa" },
  { geoId: "geoId/1938595", geoIdState: "geoId/19", city: "Iowa City", state: "Iowa" },
  { geoId: "geoId/1973335", geoIdState: "geoId/19", city: "Sioux City", state: "Iowa" },
  { geoId: "geoId/1982425", geoIdState: "geoId/19", city: "Waterloo", state: "Iowa" },
  { geoId: "geoId/2036000", geoIdState: "geoId/20", city: "Kansas City", state: "Kansas" },
  { geoId: "geoId/2038900", geoIdState: "geoId/20", city: "Lawrence", state: "Kansas" },
  { geoId: "geoId/2052575", geoIdState: "geoId/20", city: "Olathe", state: "Kansas" },
  { geoId: "geoId/2053775", geoIdState: "geoId/20", city: "Overland Park", state: "Kansas" },
  { geoId: "geoId/2071000", geoIdState: "geoId/20", city: "Topeka", state: "Kansas" },
  { geoId: "geoId/2079000", geoIdState: "geoId/20", city: "Wichita", state: "Kansas" },
  { geoId: "geoId/2146027", geoIdState: "geoId/21", city: "Lexington", state: "Kentucky" },
  { geoId: "geoId/2148006", geoIdState: "geoId/21", city: "Louisville/Jefferson County metro government (balance)", state: "Kentucky" },
  { geoId: "geoId/2205000", geoIdState: "geoId/22", city: "Baton Rouge", state: "Louisiana" },
  { geoId: "geoId/2239475", geoIdState: "geoId/22", city: "Kenner", state: "Louisiana" },
  { geoId: "geoId/2240735", geoIdState: "geoId/22", city: "Lafayette", state: "Louisiana" },
  { geoId: "geoId/2241155", geoIdState: "geoId/22", city: "Lake Charles", state: "Louisiana" },
  { geoId: "geoId/2255000", geoIdState: "geoId/22", city: "New Orleans", state: "Louisiana" },
  { geoId: "geoId/2270000", geoIdState: "geoId/22", city: "Shreveport", state: "Louisiana" },
  { geoId: "geoId/2360545", geoIdState: "geoId/23", city: "Portland", state: "Maine" },
  { geoId: "geoId/2404000", geoIdState: "geoId/24", city: "Baltimore", state: "Maryland" },
  { geoId: "geoId/2507000", geoIdState: "geoId/25", city: "Boston", state: "Massachusetts" },
  { geoId: "geoId/2509000", geoIdState: "geoId/25", city: "Brockton", state: "Massachusetts" },
  { geoId: "geoId/2511000", geoIdState: "geoId/25", city: "Cambridge", state: "Massachusetts" },
  { geoId: "geoId/2523000", geoIdState: "geoId/25", city: "Fall River", state: "Massachusetts" },
  { geoId: "geoId/2534550", geoIdState: "geoId/25", city: "Lawrence", state: "Massachusetts" },
  { geoId: "geoId/2537000", geoIdState: "geoId/25", city: "Lowell", state: "Massachusetts" },
  { geoId: "geoId/2537490", geoIdState: "geoId/25", city: "Lynn", state: "Massachusetts" },
  { geoId: "geoId/2545000", geoIdState: "geoId/25", city: "New Bedford", state: "Massachusetts" },
  { geoId: "geoId/2545560", geoIdState: "geoId/25", city: "Newton", state: "Massachusetts" },
  { geoId: "geoId/2555745", geoIdState: "geoId/25", city: "Quincy", state: "Massachusetts" },
  { geoId: "geoId/2562535", geoIdState: "geoId/25", city: "Somerville", state: "Massachusetts" },
  { geoId: "geoId/2567000", geoIdState: "geoId/25", city: "Springfield", state: "Massachusetts" },
  { geoId: "geoId/2582000", geoIdState: "geoId/25", city: "Worcester", state: "Massachusetts" },
  { geoId: "geoId/2603000", geoIdState: "geoId/26", city: "Ann Arbor", state: "Michigan" },
  { geoId: "geoId/2621000", geoIdState: "geoId/26", city: "Dearborn", state: "Michigan" },
  { geoId: "geoId/2622000", geoIdState: "geoId/26", city: "Detroit", state: "Michigan" },
  { geoId: "geoId/2627440", geoIdState: "geoId/26", city: "Farmington Hills", state: "Michigan" },
  { geoId: "geoId/2629000", geoIdState: "geoId/26", city: "Flint", state: "Michigan" },
  { geoId: "geoId/2634000", geoIdState: "geoId/26", city: "Grand Rapids", state: "Michigan" },
  { geoId: "geoId/2642160", geoIdState: "geoId/26", city: "Kalamazoo", state: "Michigan" },
  { geoId: "geoId/2646000", geoIdState: "geoId/26", city: "Lansing", state: "Michigan" },
  { geoId: "geoId/2649000", geoIdState: "geoId/26", city: "Livonia", state: "Michigan" },
  { geoId: "geoId/2669035", geoIdState: "geoId/26", city: "Rochester Hills", state: "Michigan" },
  { geoId: "geoId/2674900", geoIdState: "geoId/26", city: "Southfield", state: "Michigan" },
  { geoId: "geoId/2676460", geoIdState: "geoId/26", city: "Sterling Heights", state: "Michigan" },
  { geoId: "geoId/2680700", geoIdState: "geoId/26", city: "Troy", state: "Michigan" },
  { geoId: "geoId/2684000", geoIdState: "geoId/26", city: "Warren", state: "Michigan" },
  { geoId: "geoId/2686000", geoIdState: "geoId/26", city: "Westland", state: "Michigan" },
  { geoId: "geoId/2688940", geoIdState: "geoId/26", city: "Wyoming", state: "Michigan" },
  { geoId: "geoId/2706616", geoIdState: "geoId/27", city: "Bloomington", state: "Minnesota" },
  { geoId: "geoId/2707966", geoIdState: "geoId/27", city: "Brooklyn Park", state: "Minnesota" },
  { geoId: "geoId/2717000", geoIdState: "geoId/27", city: "Duluth", state: "Minnesota" },
  { geoId: "geoId/2743000", geoIdState: "geoId/27", city: "Minneapolis", state: "Minnesota" },
  { geoId: "geoId/2751730", geoIdState: "geoId/27", city: "Plymouth", state: "Minnesota" },
  { geoId: "geoId/2754880", geoIdState: "geoId/27", city: "Rochester", state: "Minnesota" },
  { geoId: "geoId/2758000", geoIdState: "geoId/27", city: "Saint Paul", state: "Minnesota" },
  { geoId: "geoId/2829700", geoIdState: "geoId/28", city: "Gulfport", state: "Mississippi" },
  { geoId: "geoId/2836000", geoIdState: "geoId/28", city: "Jackson", state: "Mississippi" },
  { geoId: "geoId/2915670", geoIdState: "geoId/29", city: "Columbia", state: "Missouri" },
  { geoId: "geoId/2935000", geoIdState: "geoId/29", city: "Independence", state: "Missouri" },
  { geoId: "geoId/2938000", geoIdState: "geoId/29", city: "Kansas City", state: "Missouri" },
  { geoId: "geoId/2941348", geoIdState: "geoId/29", city: "Lee's Summit", state: "Missouri" },
  { geoId: "geoId/2954074", geoIdState: "geoId/29", city: "O'Fallon", state: "Missouri" },
  { geoId: "geoId/2964550", geoIdState: "geoId/29", city: "St. Joseph", state: "Missouri" },
  { geoId: "geoId/2965000", geoIdState: "geoId/29", city: "St. Louis", state: "Missouri" },
  { geoId: "geoId/2970000", geoIdState: "geoId/29", city: "Springfield", state: "Missouri" },
  { geoId: "geoId/3006550", geoIdState: "geoId/30", city: "Billings", state: "Montana" },
  { geoId: "geoId/3050200", geoIdState: "geoId/30", city: "Missoula", state: "Montana" },
  { geoId: "geoId/3128000", geoIdState: "geoId/31", city: "Lincoln", state: "Nebraska" },
  { geoId: "geoId/3137000", geoIdState: "geoId/31", city: "Omaha", state: "Nebraska" },
  { geoId: "geoId/3231900", geoIdState: "geoId/32", city: "Henderson", state: "Nevada" },
  { geoId: "geoId/3240000", geoIdState: "geoId/32", city: "Las Vegas", state: "Nevada" },
  { geoId: "geoId/3251800", geoIdState: "geoId/32", city: "North Las Vegas", state: "Nevada" },
  { geoId: "geoId/3260600", geoIdState: "geoId/32", city: "Reno", state: "Nevada" },
  { geoId: "geoId/3268400", geoIdState: "geoId/32", city: "Sparks", state: "Nevada" },
  { geoId: "geoId/3345140", geoIdState: "geoId/33", city: "Manchester", state: "New Hampshire" },
  { geoId: "geoId/3350260", geoIdState: "geoId/33", city: "Nashua", state: "New Hampshire" },
  { geoId: "geoId/3410000", geoIdState: "geoId/34", city: "Camden", state: "New Jersey" },
  { geoId: "geoId/3413690", geoIdState: "geoId/34", city: "Clifton", state: "New Jersey" },
  { geoId: "geoId/3421000", geoIdState: "geoId/34", city: "Elizabeth", state: "New Jersey" },
  { geoId: "geoId/3436000", geoIdState: "geoId/34", city: "Jersey City", state: "New Jersey" },
  { geoId: "geoId/3451000", geoIdState: "geoId/34", city: "Newark", state: "New Jersey" },
  { geoId: "geoId/3456550", geoIdState: "geoId/34", city: "Passaic", state: "New Jersey" },
  { geoId: "geoId/3457000", geoIdState: "geoId/34", city: "Paterson", state: "New Jersey" },
  { geoId: "geoId/3474000", geoIdState: "geoId/34", city: "Trenton", state: "New Jersey" },
  { geoId: "geoId/3474630", geoIdState: "geoId/34", city: "Union City", state: "New Jersey" },
  { geoId: "geoId/3502000", geoIdState: "geoId/35", city: "Albuquerque", state: "New Mexico" },
  { geoId: "geoId/3539380", geoIdState: "geoId/35", city: "Las Cruces", state: "New Mexico" },
  { geoId: "geoId/3563460", geoIdState: "geoId/35", city: "Rio Rancho", state: "New Mexico" },
  { geoId: "geoId/3570500", geoIdState: "geoId/35", city: "Santa Fe", state: "New Mexico" },
  { geoId: "geoId/3601000", geoIdState: "geoId/36", city: "Albany", state: "New York" },
  { geoId: "geoId/3611000", geoIdState: "geoId/36", city: "Buffalo", state: "New York" },
  { geoId: "geoId/3649121", geoIdState: "geoId/36", city: "Mount Vernon", state: "New York" },
  { geoId: "geoId/3650617", geoIdState: "geoId/36", city: "New Rochelle", state: "New York" },
  { geoId: "geoId/3651000", geoIdState: "geoId/36", city: "New York City", state: "New York" },
  { geoId: "geoId/3663000", geoIdState: "geoId/36", city: "Rochester", state: "New York" },
  { geoId: "geoId/3665508", geoIdState: "geoId/36", city: "Schenectady", state: "New York" },
  { geoId: "geoId/3673000", geoIdState: "geoId/36", city: "Syracuse", state: "New York" },
  { geoId: "geoId/3684000", geoIdState: "geoId/36", city: "Yonkers", state: "New York" },
  { geoId: "geoId/3702140", geoIdState: "geoId/37", city: "Asheville", state: "North Carolina" },
  { geoId: "geoId/3710740", geoIdState: "geoId/37", city: "Cary", state: "North Carolina" },
  { geoId: "geoId/3712000", geoIdState: "geoId/37", city: "Charlotte", state: "North Carolina" },
  { geoId: "geoId/3714100", geoIdState: "geoId/37", city: "Concord", state: "North Carolina" },
  { geoId: "geoId/3719000", geoIdState: "geoId/37", city: "Durham", state: "North Carolina" },
  { geoId: "geoId/3722920", geoIdState: "geoId/37", city: "Fayetteville", state: "North Carolina" },
  { geoId: "geoId/3725580", geoIdState: "geoId/37", city: "Gastonia", state: "North Carolina" },
  { geoId: "geoId/3728000", geoIdState: "geoId/37", city: "Greensboro", state: "North Carolina" },
  { geoId: "geoId/3728080", geoIdState: "geoId/37", city: "Greenville", state: "North Carolina" },
  { geoId: "geoId/3731400", geoIdState: "geoId/37", city: "High Point", state: "North Carolina" },
  { geoId: "geoId/3734200", geoIdState: "geoId/37", city: "Jacksonville", state: "North Carolina" },
  { geoId: "geoId/3755000", geoIdState: "geoId/37", city: "Raleigh", state: "North Carolina" },
  { geoId: "geoId/3774440", geoIdState: "geoId/37", city: "Wilmington", state: "North Carolina" },
  { geoId: "geoId/3775000", geoIdState: "geoId/37", city: "Winston-Salem", state: "North Carolina" },
  { geoId: "geoId/3825700", geoIdState: "geoId/38", city: "Fargo", state: "North Dakota" },
  { geoId: "geoId/3901000", geoIdState: "geoId/39", city: "Akron", state: "Ohio" },
  { geoId: "geoId/3912000", geoIdState: "geoId/39", city: "Canton", state: "Ohio" },
  { geoId: "geoId/3915000", geoIdState: "geoId/39", city: "Cincinnati", state: "Ohio" },
  { geoId: "geoId/3916000", geoIdState: "geoId/39", city: "Cleveland", state: "Ohio" },
  { geoId: "geoId/3918000", geoIdState: "geoId/39", city: "Columbus", state: "Ohio" },
  { geoId: "geoId/3921000", geoIdState: "geoId/39", city: "Dayton", state: "Ohio" },
  { geoId: "geoId/3961000", geoIdState: "geoId/39", city: "Parma", state: "Ohio" },
  { geoId: "geoId/3977000", geoIdState: "geoId/39", city: "Toledo", state: "Ohio" },
  { geoId: "geoId/3988000", geoIdState: "geoId/39", city: "Youngstown", state: "Ohio" },
  { geoId: "geoId/4009050", geoIdState: "geoId/40", city: "Broken Arrow", state: "Oklahoma" },
  { geoId: "geoId/4023200", geoIdState: "geoId/40", city: "Edmond", state: "Oklahoma" },
  { geoId: "geoId/4041850", geoIdState: "geoId/40", city: "Lawton", state: "Oklahoma" },
  { geoId: "geoId/4052500", geoIdState: "geoId/40", city: "Norman", state: "Oklahoma" },
  { geoId: "geoId/4055000", geoIdState: "geoId/40", city: "Oklahoma City", state: "Oklahoma" },
  { geoId: "geoId/4075000", geoIdState: "geoId/40", city: "Tulsa", state: "Oklahoma" },
  { geoId: "geoId/4105350", geoIdState: "geoId/41", city: "Beaverton", state: "Oregon" },
  { geoId: "geoId/4105800", geoIdState: "geoId/41", city: "Bend", state: "Oregon" },
  { geoId: "geoId/4123850", geoIdState: "geoId/41", city: "Eugene", state: "Oregon" },
  { geoId: "geoId/4131250", geoIdState: "geoId/41", city: "Gresham", state: "Oregon" },
  { geoId: "geoId/4134100", geoIdState: "geoId/41", city: "Hillsboro", state: "Oregon" },
  { geoId: "geoId/4147000", geoIdState: "geoId/41", city: "Medford", state: "Oregon" },
  { geoId: "geoId/4159000", geoIdState: "geoId/41", city: "Portland", state: "Oregon" },
  { geoId: "geoId/4164900", geoIdState: "geoId/41", city: "Salem", state: "Oregon" },
  { geoId: "geoId/4202000", geoIdState: "geoId/42", city: "Allentown", state: "Pennsylvania" },
  { geoId: "geoId/4206088", geoIdState: "geoId/42", city: "Bethlehem", state: "Pennsylvania" },
  { geoId: "geoId/4224000", geoIdState: "geoId/42", city: "Erie", state: "Pennsylvania" },
  { geoId: "geoId/4260000", geoIdState: "geoId/42", city: "Philadelphia", state: "Pennsylvania" },
  { geoId: "geoId/4261000", geoIdState: "geoId/42", city: "Pittsburgh", state: "Pennsylvania" },
  { geoId: "geoId/4263624", geoIdState: "geoId/42", city: "Reading", state: "Pennsylvania" },
  { geoId: "geoId/4269000", geoIdState: "geoId/42", city: "Scranton", state: "Pennsylvania" },
  { geoId: "geoId/4419180", geoIdState: "geoId/44", city: "Cranston", state: "Rhode Island" },
  { geoId: "geoId/4454640", geoIdState: "geoId/44", city: "Pawtucket", state: "Rhode Island" },
  { geoId: "geoId/4459000", geoIdState: "geoId/44", city: "Providence", state: "Rhode Island" },
  { geoId: "geoId/4474300", geoIdState: "geoId/44", city: "Warwick", state: "Rhode Island" },
  { geoId: "geoId/4513330", geoIdState: "geoId/45", city: "Charleston", state: "South Carolina" },
  { geoId: "geoId/4516000", geoIdState: "geoId/45", city: "Columbia", state: "South Carolina" },
  { geoId: "geoId/4548535", geoIdState: "geoId/45", city: "Mount Pleasant", state: "South Carolina" },
  { geoId: "geoId/4550875", geoIdState: "geoId/45", city: "North Charleston", state: "South Carolina" },
  { geoId: "geoId/4561405", geoIdState: "geoId/45", city: "Rock Hill", state: "South Carolina" },
  { geoId: "geoId/4652980", geoIdState: "geoId/46", city: "Rapid City", state: "South Dakota" },
  { geoId: "geoId/4659020", geoIdState: "geoId/46", city: "Sioux Falls", state: "South Dakota" },
  { geoId: "geoId/4714000", geoIdState: "geoId/47", city: "Chattanooga", state: "Tennessee" },
  { geoId: "geoId/4715160", geoIdState: "geoId/47", city: "Clarksville", state: "Tennessee" },
  { geoId: "geoId/4740000", geoIdState: "geoId/47", city: "Knoxville", state: "Tennessee" },
  { geoId: "geoId/4748000", geoIdState: "geoId/47", city: "Memphis", state: "Tennessee" },
  { geoId: "geoId/4751560", geoIdState: "geoId/47", city: "Murfreesboro", state: "Tennessee" },
  { geoId: "geoId/4752006", geoIdState: "geoId/47", city: "Nashville-Davidson metropolitan government (balance)", state: "Tennessee" },
  { geoId: "geoId/4801000", geoIdState: "geoId/48", city: "Abilene", state: "Texas" },
  { geoId: "geoId/4801924", geoIdState: "geoId/48", city: "Allen", state: "Texas" },
  { geoId: "geoId/4803000", geoIdState: "geoId/48", city: "Amarillo", state: "Texas" },
  { geoId: "geoId/4804000", geoIdState: "geoId/48", city: "Arlington", state: "Texas" },
  { geoId: "geoId/4805000", geoIdState: "geoId/48", city: "Austin", state: "Texas" },
  { geoId: "geoId/4806128", geoIdState: "geoId/48", city: "Baytown", state: "Texas" },
  { geoId: "geoId/4807000", geoIdState: "geoId/48", city: "Beaumont", state: "Texas" },
  { geoId: "geoId/4810768", geoIdState: "geoId/48", city: "Brownsville", state: "Texas" },
  { geoId: "geoId/4810912", geoIdState: "geoId/48", city: "Bryan", state: "Texas" },
  { geoId: "geoId/4813024", geoIdState: "geoId/48", city: "Carrollton", state: "Texas" },
  { geoId: "geoId/4815976", geoIdState: "geoId/48", city: "College Station", state: "Texas" },
  { geoId: "geoId/4817000", geoIdState: "geoId/48", city: "Corpus Christi", state: "Texas" },
  { geoId: "geoId/4819000", geoIdState: "geoId/48", city: "Dallas", state: "Texas" },
  { geoId: "geoId/4819972", geoIdState: "geoId/48", city: "Denton", state: "Texas" },
  { geoId: "geoId/4822660", geoIdState: "geoId/48", city: "Edinburg", state: "Texas" },
  { geoId: "geoId/4824000", geoIdState: "geoId/48", city: "El Paso", state: "Texas" },
  { geoId: "geoId/4827000", geoIdState: "geoId/48", city: "Fort Worth", state: "Texas" },
  { geoId: "geoId/4827684", geoIdState: "geoId/48", city: "Frisco", state: "Texas" },
  { geoId: "geoId/4829000", geoIdState: "geoId/48", city: "Garland", state: "Texas" },
  { geoId: "geoId/4830464", geoIdState: "geoId/48", city: "Grand Prairie", state: "Texas" },
  { geoId: "geoId/4835000", geoIdState: "geoId/48", city: "Houston", state: "Texas" },
  { geoId: "geoId/4837000", geoIdState: "geoId/48", city: "Irving", state: "Texas" },
  { geoId: "geoId/4839148", geoIdState: "geoId/48", city: "Killeen", state: "Texas" },
  { geoId: "geoId/4841464", geoIdState: "geoId/48", city: "Laredo", state: "Texas" },
  { geoId: "geoId/4841980", geoIdState: "geoId/48", city: "League City", state: "Texas" },
  { geoId: "geoId/4842508", geoIdState: "geoId/48", city: "Lewisville", state: "Texas" },
  { geoId: "geoId/4843888", geoIdState: "geoId/48", city: "Longview", state: "Texas" },
  { geoId: "geoId/4845000", geoIdState: "geoId/48", city: "Lubbock", state: "Texas" },
  { geoId: "geoId/4845384", geoIdState: "geoId/48", city: "McAllen", state: "Texas" },
  { geoId: "geoId/4845744", geoIdState: "geoId/48", city: "McKinney", state: "Texas" },
  { geoId: "geoId/4847892", geoIdState: "geoId/48", city: "Mesquite", state: "Texas" },
  { geoId: "geoId/4848072", geoIdState: "geoId/48", city: "Midland", state: "Texas" },
  { geoId: "geoId/4848768", geoIdState: "geoId/48", city: "Mission", state: "Texas" },
  { geoId: "geoId/4848804", geoIdState: "geoId/48", city: "Missouri City", state: "Texas" },
  { geoId: "geoId/4853388", geoIdState: "geoId/48", city: "Odessa", state: "Texas" },
  { geoId: "geoId/4856000", geoIdState: "geoId/48", city: "Pasadena", state: "Texas" },
  { geoId: "geoId/4856348", geoIdState: "geoId/48", city: "Pearland", state: "Texas" },
  { geoId: "geoId/4857200", geoIdState: "geoId/48", city: "Pharr", state: "Texas" },
  { geoId: "geoId/4858016", geoIdState: "geoId/48", city: "Plano", state: "Texas" },
  { geoId: "geoId/4861796", geoIdState: "geoId/48", city: "Richardson", state: "Texas" },
  { geoId: "geoId/4863500", geoIdState: "geoId/48", city: "Round Rock", state: "Texas" },
  { geoId: "geoId/4864472", geoIdState: "geoId/48", city: "San Angelo", state: "Texas" },
  { geoId: "geoId/4865000", geoIdState: "geoId/48", city: "San Antonio", state: "Texas" },
  { geoId: "geoId/4870808", geoIdState: "geoId/48", city: "Sugar Land", state: "Texas" },
  { geoId: "geoId/4874144", geoIdState: "geoId/48", city: "Tyler", state: "Texas" },
  { geoId: "geoId/4876000", geoIdState: "geoId/48", city: "Waco", state: "Texas" },
  { geoId: "geoId/4879000", geoIdState: "geoId/48", city: "Wichita Falls", state: "Texas" },
  { geoId: "geoId/4943660", geoIdState: "geoId/49", city: "Layton", state: "Utah" },
  { geoId: "geoId/4955980", geoIdState: "geoId/49", city: "Ogden", state: "Utah" },
  { geoId: "geoId/4957300", geoIdState: "geoId/49", city: "Orem", state: "Utah" },
  { geoId: "geoId/4962470", geoIdState: "geoId/49", city: "Provo", state: "Utah" },
  { geoId: "geoId/4965330", geoIdState: "geoId/49", city: "St. George", state: "Utah" },
  { geoId: "geoId/4967000", geoIdState: "geoId/49", city: "Salt Lake City", state: "Utah" },
  { geoId: "geoId/4967440", geoIdState: "geoId/49", city: "Sandy", state: "Utah" },
  { geoId: "geoId/4982950", geoIdState: "geoId/49", city: "West Jordan", state: "Utah" },
  { geoId: "geoId/4983470", geoIdState: "geoId/49", city: "West Valley City", state: "Utah" },
  { geoId: "geoId/5010675", geoIdState: "geoId/50", city: "Burlington", state: "Vermont" },
  { geoId: "geoId/5101000", geoIdState: "geoId/51", city: "Alexandria", state: "Virginia" },
  { geoId: "geoId/5116000", geoIdState: "geoId/51", city: "Chesapeake", state: "Virginia" },
  { geoId: "geoId/5135000", geoIdState: "geoId/51", city: "Hampton", state: "Virginia" },
  { geoId: "geoId/5147672", geoIdState: "geoId/51", city: "Lynchburg", state: "Virginia" },
  { geoId: "geoId/5156000", geoIdState: "geoId/51", city: "Newport News", state: "Virginia" },
  { geoId: "geoId/5157000", geoIdState: "geoId/51", city: "Norfolk", state: "Virginia" },
  { geoId: "geoId/5164000", geoIdState: "geoId/51", city: "Portsmouth", state: "Virginia" },
  { geoId: "geoId/5167000", geoIdState: "geoId/51", city: "Richmond", state: "Virginia" },
  { geoId: "geoId/5168000", geoIdState: "geoId/51", city: "Roanoke", state: "Virginia" },
  { geoId: "geoId/5176432", geoIdState: "geoId/51", city: "Suffolk", state: "Virginia" },
  { geoId: "geoId/5182000", geoIdState: "geoId/51", city: "Virginia Beach", state: "Virginia" },
  { geoId: "geoId/5303180", geoIdState: "geoId/53", city: "Auburn", state: "Washington" },
  { geoId: "geoId/5305210", geoIdState: "geoId/53", city: "Bellevue", state: "Washington" },
  { geoId: "geoId/5305280", geoIdState: "geoId/53", city: "Bellingham", state: "Washington" },
  { geoId: "geoId/5322640", geoIdState: "geoId/53", city: "Everett", state: "Washington" },
  { geoId: "geoId/5323515", geoIdState: "geoId/53", city: "Federal Way", state: "Washington" },
  { geoId: "geoId/5335275", geoIdState: "geoId/53", city: "Kennewick", state: "Washington" },
  { geoId: "geoId/5335415", geoIdState: "geoId/53", city: "Kent", state: "Washington" },
  { geoId: "geoId/5357745", geoIdState: "geoId/53", city: "Renton", state: "Washington" },
  { geoId: "geoId/5363000", geoIdState: "geoId/53", city: "Seattle", state: "Washington" },
  { geoId: "geoId/5367000", geoIdState: "geoId/53", city: "Spokane", state: "Washington" },
  { geoId: "geoId/5367167", geoIdState: "geoId/53", city: "Spokane Valley", state: "Washington" },
  { geoId: "geoId/5370000", geoIdState: "geoId/53", city: "Tacoma", state: "Washington" },
  { geoId: "geoId/5374060", geoIdState: "geoId/53", city: "Vancouver", state: "Washington" },
  { geoId: "geoId/5380010", geoIdState: "geoId/53", city: "Yakima", state: "Washington" },
  { geoId: "geoId/5414600", geoIdState: "geoId/54", city: "Charleston", state: "West Virginia" },
  { geoId: "geoId/5502375", geoIdState: "geoId/55", city: "Appleton", state: "Wisconsin" },
  { geoId: "geoId/5531000", geoIdState: "geoId/55", city: "Green Bay", state: "Wisconsin" },
  { geoId: "geoId/5539225", geoIdState: "geoId/55", city: "Kenosha", state: "Wisconsin" },
  { geoId: "geoId/5548000", geoIdState: "geoId/55", city: "Madison", state: "Wisconsin" },
  { geoId: "geoId/5553000", geoIdState: "geoId/55", city: "Milwaukee", state: "Wisconsin" },
  { geoId: "geoId/5566000", geoIdState: "geoId/55", city: "Racine", state: "Wisconsin" },
  { geoId: "geoId/5584250", geoIdState: "geoId/55", city: "Waukesha", state: "Wisconsin" },
  { geoId: "geoId/5613900", geoIdState: "geoId/56", city: "Cheyenne", state: "Wyoming" },
]
