export type Styles = {
  'error': string;
  'textField--lg--dark': string;
  'textField--lg--dark--Licon1': string;
  'textField--lg--dark--Licon2': string;
  'textField--lg--dark--Licon3': string;
  'textField--lg--dark--Ricon1': string;
  'textField--lg--dark--Ricon2': string;
  'textField--lg--dark--Ricon3': string;
  'textField--lg--high-contrast': string;
  'textField--lg--high-contrast--Licon1': string;
  'textField--lg--high-contrast--Licon2': string;
  'textField--lg--high-contrast--Licon3': string;
  'textField--lg--high-contrast--Ricon1': string;
  'textField--lg--high-contrast--Ricon2': string;
  'textField--lg--high-contrast--Ricon3': string;
  'textField--lg--light': string;
  'textField--lg--light--Licon1': string;
  'textField--lg--light--Licon2': string;
  'textField--lg--light--Licon3': string;
  'textField--lg--light--Ricon1': string;
  'textField--lg--light--Ricon2': string;
  'textField--lg--light--Ricon3': string;
  'textField--md--dark': string;
  'textField--md--dark--Licon1': string;
  'textField--md--dark--Licon2': string;
  'textField--md--dark--Licon3': string;
  'textField--md--dark--Ricon1': string;
  'textField--md--dark--Ricon2': string;
  'textField--md--dark--Ricon3': string;
  'textField--md--high-contrast': string;
  'textField--md--high-contrast--Licon1': string;
  'textField--md--high-contrast--Licon2': string;
  'textField--md--high-contrast--Licon3': string;
  'textField--md--high-contrast--Ricon1': string;
  'textField--md--high-contrast--Ricon2': string;
  'textField--md--high-contrast--Ricon3': string;
  'textField--md--light': string;
  'textField--md--light--Licon1': string;
  'textField--md--light--Licon2': string;
  'textField--md--light--Licon3': string;
  'textField--md--light--Ricon1': string;
  'textField--md--light--Ricon2': string;
  'textField--md--light--Ricon3': string;
  'textField--outerContainer--dark': string;
  'textField--outerContainer--high-contrast': string;
  'textField--outerContainer--light': string;
  'textField--sm--dark': string;
  'textField--sm--dark--Licon1': string;
  'textField--sm--dark--Licon2': string;
  'textField--sm--dark--Licon3': string;
  'textField--sm--dark--Ricon1': string;
  'textField--sm--dark--Ricon2': string;
  'textField--sm--dark--Ricon3': string;
  'textField--sm--high-contrast': string;
  'textField--sm--high-contrast--Licon1': string;
  'textField--sm--high-contrast--Licon2': string;
  'textField--sm--high-contrast--Licon3': string;
  'textField--sm--high-contrast--Ricon1': string;
  'textField--sm--high-contrast--Ricon2': string;
  'textField--sm--high-contrast--Ricon3': string;
  'textField--sm--light': string;
  'textField--sm--light--Licon1': string;
  'textField--sm--light--Licon2': string;
  'textField--sm--light--Licon3': string;
  'textField--sm--light--Ricon1': string;
  'textField--sm--light--Ricon2': string;
  'textField--sm--light--Ricon3': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
