export type Styles = {
  'btn-circle-accent-var1': string;
  'btn-circle-hico-var1': string;
  'btn-circle-link-var1': string;
  'btn-circle-negative-var1': string;
  'btn-circle-primary-var1': string;
  'btn-circle-primary-var2': string;
  'btn-circle-primary-var3': string;
  'btn-circle-secondary-var1': string;
  'btn-circle-secondary-var2': string;
  'btn-circle-static-var1': string;
  'btn-circle-static-var2': string;
  'btn-icon': string;
  'btn-large-accent-var1': string;
  'btn-large-hico-var1': string;
  'btn-large-link-var1': string;
  'btn-large-negative-var1': string;
  'btn-large-primary-var1': string;
  'btn-large-primary-var2': string;
  'btn-large-primary-var3': string;
  'btn-large-secondary-var1': string;
  'btn-large-secondary-var2': string;
  'btn-large-static-var1': string;
  'btn-large-static-var2': string;
  'btn-medium-accent-var1': string;
  'btn-medium-hico-var1': string;
  'btn-medium-link-var1': string;
  'btn-medium-negative-var1': string;
  'btn-medium-primary-var1': string;
  'btn-medium-primary-var2': string;
  'btn-medium-primary-var3': string;
  'btn-medium-secondary-var1': string;
  'btn-medium-secondary-var2': string;
  'btn-medium-static-var1': string;
  'btn-medium-static-var2': string;
  'btn-small-accent-var1': string;
  'btn-small-hico-var1': string;
  'btn-small-link-var1': string;
  'btn-small-negative-var1': string;
  'btn-small-primary-var1': string;
  'btn-small-primary-var2': string;
  'btn-small-primary-var3': string;
  'btn-small-secondary-var1': string;
  'btn-small-secondary-var2': string;
  'btn-small-static-var1': string;
  'btn-small-static-var2': string;
  'btn-xsmall-accent-var1': string;
  'btn-xsmall-hico-var1': string;
  'btn-xsmall-link-var1': string;
  'btn-xsmall-negative-var1': string;
  'btn-xsmall-primary-var1': string;
  'btn-xsmall-primary-var2': string;
  'btn-xsmall-primary-var3': string;
  'btn-xsmall-secondary-var1': string;
  'btn-xsmall-secondary-var2': string;
  'btn-xsmall-static-var1': string;
  'btn-xsmall-static-var2': string;
  'typo_code-lgText': string;
  'typo_code-mText': string;
  'typo_code-smText': string;
  'typo_code-xsText': string;
  'typo_text-lgText': string;
  'typo_text-mText': string;
  'typo_text-smText': string;
  'typo_text-xlText': string;
  'typo_text-xsText': string;
  'typo_title-display1': string;
  'typo_title-displaySub': string;
  'typo_title-title1': string;
  'typo_title-title2': string;
  'typo_title-title3': string;
  'typo_title-title4': string;
  'typo_title-title5': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
